language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.2
otp_release:
  - 20.2
sudo: false
env:
  - MIX_ENV=test ECTO_PGSQL_USER=postgres ECTO_PGSQL_PASSWORD=
script:
  - mix test
  # - mix coveralls.travis
after_script:
  - mix credo
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
